"""location_data table

Revision ID: 2fa01f325708
Revises: 
Create Date: 2021-12-02 23:12:02.420946

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2fa01f325708'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('location_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('latitude', sa.String(length=128), nullable=True),
    sa.Column('longitude', sa.String(length=128), nullable=True),
    sa.Column('address', sa.String(length=512), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_location_data_latitude'), 'location_data', ['latitude'], unique=False)
    op.create_index(op.f('ix_location_data_longitude'), 'location_data', ['longitude'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_location_data_longitude'), table_name='location_data')
    op.drop_index(op.f('ix_location_data_latitude'), table_name='location_data')
    op.drop_table('location_data')
    # ### end Alembic commands ###
